<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recibir</title>
</head>
<body>
    <h1>Se guardaron tus respuestas</h1>
    <?php
    $nombre = $_POST['nombre'];
    $correo = $_POST['correo'];
    $fecha_nacimiento = $_POST['fecha de nacimiento'];
    $telefono = $_POST['telefono'];
</body>
</html>